CREATE TABLE `CLASS` (
    `CLASS_ID` CHAR(3) PRIMARY KEY,
    `COURSE_ID` CHAR(3),
    `TEACHER_ID` CHAR(3),
    `ROOM_ID` CHAR(4)
);

CREATE TABLE `ROOM` (
    `ROOM_ID` CHAR(4) PRIMARY KEY,
    `ROOM_TYPE` VARCHAR(54)
);

CREATE TABLE `COURSE` (
    `COURSE_ID` CHAR(3) PRIMARY KEY,
    `COURSE_NAME` VARCHAR(70),
    `COURSE_CREDIT` INT
);

CREATE TABLE `TEACHER` (
    `TEACHER_ID` CHAR(3) PRIMARY KEY,
    `TEACHER_FNAME` VARCHAR(20),
    `TEACHER_LNAME` VARCHAR(70)
);

ALTER TABLE `CLASS`
    DROP COLUMN `ROOM_ID`;

ALTER TABLE `ROOM`
    MODIFY `ROOM_TYPE` VARCHAR(30),
    ADD COLUMN `ROOM_CAPACITY` INT;

ALTER TABLE `COURSE`
    MODIFY `COURSE_NAME` TEXT,
    ADD COLUMN `COURSE_DESCRIPTION` TEXT AFTER `COURSE_NAME`;

ALTER TABLE `TEACHER`
    MODIFY `TEACHER_FNAME` VARCHAR(30),
    ADD COLUMN `TEACHE
