CREATE TABLE `CLASS` (
    `CLASS_ID` CHAR(3) PRIMARY KEY,
    `COURSE_ID` CHAR(3),
    `TEACHER_ID` CHAR(3),
    `ROOM_ID` CHAR(4)
);

CREATE TABLE `ROOM` (
    `ROOM_ID` CHAR(4) PRIMARY KEY,
    `ROOM_TYPE` VARCHAR(54)
);

CREATE TABLE `COURSE` (
    `COURSE_ID` CHAR(3) PRIMARY KEY,
    `COURSE_NAME` VARCHAR(70),
    `COURSE_CREDIT` INT
);

CREATE TABLE `TEACHER` (
    `TEACHER_ID` CHAR(3) PRIMARY KEY,
    `TEACHER_FNAME` VARCHAR(20),
    `TEACHER_LNAME` VARCHAR(70)
);
