ALTER TABLE `CLASS`
    DROP COLUMN `ROOM_ID`;

ALTER TABLE `ROOM`
    MODIFY `ROOM_TYPE` VARCHAR(30),
    ADD COLUMN `ROOM_CAPACITY` INT;

ALTER TABLE `COURSE`
    MODIFY `COURSE_NAME` TEXT,
    ADD COLUMN `COURSE_DESCRIPTION` TEXT AFTER `COURSE_NAME`;

ALTER TABLE `TEACHER`
    MODIFY `TEACHER_FNAME` VARCHAR(30),
    ADD COLUMN `TEACHER_AGE` INT;
